name: Cetak APK Stick War 2 Instan
on: [push]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil File Proyek
      uses: actions/checkout@v4
    - name: Bungkus Menjadi APK
      uses: ttechnics/html5-to-apk-compiler-action@v2
      with:
        app_name: "Stick War 2 HP"
        package_name: "com.saya.stickwar2"
        project_dir: "."
    - name: Ambil File APK Jadi
      uses: actions/upload-artifact@v4
      with:
        name: StickWar2_Offline_Port
        path: "*.apk"
        
