name: Cetak APK Stick War 2 Resmi
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Ambil File Proyek
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Buat Struktur Aplikasi
      run: |
        mkdir -p app/src/main/assets/www
        cp index.html app/src/main/assets/www/
        cp stickwar2.swf app/src/main/assets/www/

    - name: Unduh Alat Bungkus APK
      run: |
        wget https://github.com -O base.apk
        mkdir unzip_apk
        unzip base.apk -d unzip_apk/
        cp -r app/src/main/assets/www/* unzip_apk/assets/www/
        cd unzip_apk
        zip -r ../StickWar2_HP.apk .

    - name: Simpan Hasil APK
      uses: actions/upload-artifact@v4
      with:
        name: StickWar2_Offline_Port
        path: StickWar2_HP.apk
        
